### ISSUE TITLE
Curate Other Implementations of Paseto

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/paseto#45]
Languages desired:

- [x] C
- [x] C# (.NET)
- [x] Go
- [x] Java
- [x] Javascript
- [ ] Perl
- [x] Python
- [ ] Ruby
- [x] Rust
- [x] Swift
- Feel free to suggest other languages too.

**Comment by aidantwoods** [comment]
I started on a Swift implementation based on the PHP library if you also wanted Swift?

**Comment by paragonie-scott** [comment]
Swift would be great too! I was just listing the languages I know that aren't obscure (e.g. ColdFusion or Delphi)

**Comment by rlittlefield** [comment]
I just released an early version of a fork of pypast that was diverged so much it basically just has the pre_auth_encode function leftover. Currently just supports "local", but I'm interesting in getting the rest. It even has unit tests for encrypt/decrypt, matching the ones in Version2VectorTest.php.

https://github.com/rlittlefield/pypaseto
https://pypi.python.org/pypi/paseto

**Comment by SecurityInsanity** [comment]
We have now gotten approval at work to open source our rust implementation for Paseto: https://github.com/instructure/paseto

**Comment by paragonie-scott** [comment]
I'm going to update the README with links to these implementations this evening. :D

**Comment by aidantwoods** [comment]
Righto, here's Swift: https://github.com/aidantwoods/swift-paseto

**Comment by nask0** [comment]
It should be great to see JavaScript implementation.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/paseto/commit/c11bedf9af32d1ff0bca64043d4972ba63ec8d30 :P

**Comment by idaviddesmet** [comment]
Just released the library I was working on for .NET which supports v1 and v2 public purpose. :-]
[https://github.com/idaviddesmet/paseto-dotnet](https://github.com/idaviddesmet/paseto-dotnet)

**Comment by dustinsoftware** [comment]
My [Paseto.NET](https://github.com/dustinsoftware/Paseto.Net/) port just hit 1.0.0 and now fully supports v2 local and public tokens

**Comment by martinstreicher** [comment]
Anyone working on a Ruby version of this?

**Comment by minus7** [comment]
We have just published our C implementation: https://github.com/authenticvision/libpaseto

**Comment by paragonie-scott** [comment]
Awesome @minus7 :)

Okay, I'm going to close this issue. We still don't have Ruby or Perl bindings, but they were added to the list arbitrarily and the goal of the ticket was to have some means of curating the different implementations, and now that we have https://paseto.io, this is resolved.

Thanks everyone for implementing Paseto in your favorite languages and sharing them here. 👍
